version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./app:/var/www/html:ro
    depends_on:
      - php
    restart: unless-stopped

  php:
    image: php:8.2-fpm
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=iptv
      - DB_USER=iptv
      - DB_PASS=iptv_pass
      - SOURCE_M3U=https://cdn.jsdelivr.net/gh/barisha-app/iptv@main/listE.m3u
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=iptv
      - MARIADB_USER=iptv
      - MARIADB_PASSWORD=iptv_pass
      - MARIADB_ROOT_PASSWORD=root_pass
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    restart: unless-stopped
